// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkBee.Infrastructure.Context;

namespace ParkBee.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210619094646_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkBee.Core.Domain.GarageAggregate.Entities.Door", b =>
                {
                    b.Property<Guid>("DoorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GarageDetailGarageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DoorId");

                    b.HasIndex("GarageDetailGarageId");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("ParkBee.Core.Domain.GarageAggregate.Entities.GarageDetail", b =>
                {
                    b.Property<Guid>("GarageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GarageName")
                        .HasColumnName("GarageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBarrier")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<int>("Latitide")
                        .HasColumnType("int");

                    b.Property<int>("Longitude")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GarageId");

                    b.HasIndex("AddressId");

                    b.ToTable("Garages");
                });

            modelBuilder.Entity("ParkBee.Core.Domain.GarageAggregate.Entities.GarageDoorStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LastStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("currentStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GarageDoorStatusHistory");
                });

            modelBuilder.Entity("ParkBee.Core.Domain.GarageAggregate.ValueObjects.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnName("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnName("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnName("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnName("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("ParkBee.Core.Domain.GarageAggregate.Entities.Door", b =>
                {
                    b.HasOne("ParkBee.Core.Domain.GarageAggregate.Entities.GarageDetail", null)
                        .WithMany("Doors")
                        .HasForeignKey("GarageDetailGarageId");
                });

            modelBuilder.Entity("ParkBee.Core.Domain.GarageAggregate.Entities.GarageDetail", b =>
                {
                    b.HasOne("ParkBee.Core.Domain.GarageAggregate.ValueObjects.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
