version: '3.4'

services:
  parkbee-sqlserver:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "SQL@12345"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"
        container_name: "ParkBeeDataBase"
  parkbee.api:
    image: ${DOCKER_REGISTRY-}parkbeeapi
    build:
      context: .
      dockerfile: Src/Presentation/ParkBee.Api/Dockerfile
    depends_on:
      - parkbee-sqlserver
